import { useState } from 'react';
import { ActivityIndicator, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Button } from '@/components/ui/button';
import { colors, radius, spacing, typography } from '@/constants/design-system';
import { useAuth } from '@/features/auth/auth-provider';
export default function SignInScreen() {
  const { configurationError, identity, session, signIn, signOut } = useAuth(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState<string | null>(null); const [isSubmitting, setIsSubmitting] = useState(false);
  const blockedAccount = Boolean(session && identity?.status !== 'active');
  async function handleSignIn() { setError(null); setIsSubmitting(true); const message = await signIn(email, password); setError(message); setIsSubmitting(false); }
  return <SafeAreaView style={styles.screen}><View style={styles.content}><Text style={styles.brand}>LogIn</Text><View style={styles.form}><Text style={styles.title}>{blockedAccount ? 'Account unavailable' : 'Welcome back'}</Text><Text style={styles.subtitle}>{configurationError ? 'Add the two public Supabase values to .env.local, then reload the app.' : blockedAccount ? 'Your account is not active. Contact your organization administrator.' : 'Sign in with your work account.'}</Text>{!configurationError && !blockedAccount && <><TextInput accessibilityLabel="Work email" autoCapitalize="none" autoComplete="email" keyboardType="email-address" onChangeText={setEmail} placeholder="Work email" style={styles.input} value={email} /><TextInput accessibilityLabel="Password" autoComplete="current-password" onChangeText={setPassword} placeholder="Password" secureTextEntry style={styles.input} value={password} /><Button accessibilityLabel="Sign in" onPress={() => void handleSignIn()}>{isSubmitting ? 'Signing in…' : 'Sign in'}</Button></>}{blockedAccount && <Button accessibilityLabel="Sign out" onPress={() => void signOut()}>Sign out</Button>}{isSubmitting && <ActivityIndicator color={colors.primary} />}{error && <Text accessibilityLiveRegion="polite" style={styles.error}>{error}</Text>}</View></View></SafeAreaView>;
}
const styles = StyleSheet.create({ screen: { backgroundColor: colors.canvas, flex: 1 }, content: { flex: 1, justifyContent: 'space-between', padding: spacing.lg }, brand: { color: colors.ink, fontSize: 24, fontWeight: '800' }, form: { gap: spacing.md, marginBottom: 'auto', marginTop: 'auto' }, title: { color: colors.ink, ...typography.title }, subtitle: { color: colors.muted, ...typography.subtitle }, input: { backgroundColor: colors.white, borderColor: '#D5DDEA', borderRadius: radius.md, borderWidth: 1, color: colors.ink, fontSize: 16, padding: spacing.md }, error: { color: '#B42318', ...typography.body } });
